domains:
  - domain: gagana-tokelau.org.nz
    organization: Gagana Tokelau (language and education resources)
    sector: Education
  - domain: teletokco.tk
    organization: Telecommunication Tokelau Corporation (Teletok)
    sector: Telecommunications
  - domain: tokelau.org.nz
    organization: Government of Tokelau
    sector: Government
